[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { workspace = true, features = ["attributes"] }
toml.workspace = true
cherry = { package = "cherry", path = "../cherry" }


